default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  user: postgres
  password: password
  database: lollie_bot_development
  host: localhost
  pool: 30

test:
  <<: *default
  user: postgres
  password: password
  database: lollie_bot_test
  host: localhost
  pool: 30

production:
  <<: *default
  database: db/production.sqlite3
